name: Build fat-jar

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project (skip tests)
        run: mvn -DskipTests clean package

      # ---- Show what has been produced -------------------------------
      - name: List target directory
        run: |
          echo "===== Contents of target/ ====="
          ls -l target

      # ---- Upload every JAR we find ----------------------------------
      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: pnl-report-jars
          path: target/*.jar
